### ISSUE TITLE
Update to moondream2 to include Flash Attention 2.0

### ISSUE THREAD

**Issue by Govind-S-B** [lucataco/cog-moondream2#1]
Vik just updated the model to add support for flash attention 2.0 and a few other stuff.
Ref : https://twitter.com/vikhyatk/status/1765532280926421094  

The model file has been updated , I dont know exactly how cog works and if the model needs to be reuploaded ( I think i read that you need to somewhere )

Enable flash attention as well :
![image](https://github.com/lucataco/cog-moondream2/assets/62943847/f6a54245-49e2-46e8-86d0-cbf4016580cb)

**Comment by lucataco** [comment]
Done!
